export type Rarity = "common" | "uncommon" | "rare" | "legendary";
export type Habitat = "freshwater" | "saltwater" | "brackish" | "reef" | "deep-sea";

export interface FishSpecies {
  id: string;
  dexNumber: number;
  commonName: string;
  scientificName: string;
  habitat: Habitat;
  rarity: Rarity;
  maxLengthCm: number;
  regions: string[];
  diet: string;
  description: string;
}

export const FISH_SPECIES: FishSpecies[] = [
  {
    id: "rainbow-trout",
    dexNumber: 1,
    commonName: "Rainbow Trout",
    scientificName: "Oncorhynchus mykiss",
    habitat: "freshwater",
    rarity: "common",
    maxLengthCm: 76,
    regions: ["North America", "Europe"],
    diet: "Insects, crustaceans, small fish",
    description:
      "Iridescent pink stripe along the flank. A staple of cold mountain streams and stocked lakes.",
  },
  {
    id: "largemouth-bass",
    dexNumber: 2,
    commonName: "Largemouth Bass",
    scientificName: "Micropterus salmoides",
    habitat: "freshwater",
    rarity: "common",
    maxLengthCm: 97,
    regions: ["North America"],
    diet: "Fish, frogs, crayfish",
    description: "Ambush predator lurking in weed beds and under docks.",
  },
  {
    id: "bluegill",
    dexNumber: 3,
    commonName: "Bluegill",
    scientificName: "Lepomis macrochirus",
    habitat: "freshwater",
    rarity: "common",
    maxLengthCm: 41,
    regions: ["North America"],
    diet: "Insects, zooplankton",
    description: "Small panfish with a dark ear flap and orange breast.",
  },
  {
    id: "brook-trout",
    dexNumber: 4,
    commonName: "Brook Trout",
    scientificName: "Salvelinus fontinalis",
    habitat: "freshwater",
    rarity: "uncommon",
    maxLengthCm: 55,
    regions: ["North America"],
    diet: "Insects, small fish",
    description: "Marbled back with red spots ringed in blue haloes.",
  },
  {
    id: "northern-pike",
    dexNumber: 5,
    commonName: "Northern Pike",
    scientificName: "Esox lucius",
    habitat: "freshwater",
    rarity: "uncommon",
    maxLengthCm: 150,
    regions: ["North America", "Europe", "Asia"],
    diet: "Fish, waterfowl, amphibians",
    description: "Torpedo-shaped predator with a duckbill snout and rows of teeth.",
  },
  {
    id: "clownfish",
    dexNumber: 6,
    commonName: "Ocellaris Clownfish",
    scientificName: "Amphiprion ocellaris",
    habitat: "reef",
    rarity: "uncommon",
    maxLengthCm: 11,
    regions: ["Indo-Pacific"],
    diet: "Algae, zooplankton",
    description: "Lives in mutualistic symbiosis with sea anemones.",
  },
  {
    id: "mahi-mahi",
    dexNumber: 7,
    commonName: "Mahi-Mahi",
    scientificName: "Coryphaena hippurus",
    habitat: "saltwater",
    rarity: "rare",
    maxLengthCm: 210,
    regions: ["Tropical oceans worldwide"],
    diet: "Flying fish, squid, crustaceans",
    description: "Electric blue-green-gold. Fades to silver moments after capture.",
  },
  {
    id: "bluefin-tuna",
    dexNumber: 8,
    commonName: "Atlantic Bluefin Tuna",
    scientificName: "Thunnus thynnus",
    habitat: "saltwater",
    rarity: "rare",
    maxLengthCm: 458,
    regions: ["Atlantic Ocean", "Mediterranean"],
    diet: "Herring, mackerel, squid",
    description: "Warm-blooded giant capable of transoceanic migrations.",
  },
  {
    id: "great-white",
    dexNumber: 9,
    commonName: "Great White Shark",
    scientificName: "Carcharodon carcharias",
    habitat: "saltwater",
    rarity: "legendary",
    maxLengthCm: 610,
    regions: ["Coastal temperate seas"],
    diet: "Seals, sea lions, fish",
    description: "Apex predator. Countershaded gray above, white below.",
  },
  {
    id: "oarfish",
    dexNumber: 10,
    commonName: "Giant Oarfish",
    scientificName: "Regalecus glesne",
    habitat: "deep-sea",
    rarity: "legendary",
    maxLengthCm: 1100,
    regions: ["Global deep waters"],
    diet: "Krill, small squid",
    description: "Ribbon-like body with a scarlet dorsal crest. Origin of sea serpent lore.",
  },
  {
    id: "anglerfish",
    dexNumber: 11,
    commonName: "Humpback Anglerfish",
    scientificName: "Melanocetus johnsonii",
    habitat: "deep-sea",
    rarity: "legendary",
    maxLengthCm: 18,
    regions: ["Global deep waters"],
    diet: "Small fish, crustaceans",
    description: "Bioluminescent esca dangles above needle-like teeth.",
  },
  {
    id: "coelacanth",
    dexNumber: 12,
    commonName: "Coelacanth",
    scientificName: "Latimeria chalumnae",
    habitat: "deep-sea",
    rarity: "legendary",
    maxLengthCm: 200,
    regions: ["Western Indian Ocean"],
    diet: "Fish, cephalopods",
    description: "Lobe-finned living fossil once thought extinct for 66 million years.",
  },
  {
    id: "yellowfin-tuna",
    dexNumber: 13,
    commonName: "Yellowfin Tuna",
    scientificName: "Thunnus albacares",
    habitat: "saltwater",
    rarity: "rare",
    maxLengthCm: 239,
    regions: ["Tropical & subtropical oceans"],
    diet: "Fish, squid, crustaceans",
    description: "Long yellow finlets and sickle-shaped second dorsal fin.",
  },
  {
    id: "atlantic-salmon",
    dexNumber: 14,
    commonName: "Atlantic Salmon",
    scientificName: "Salmo salar",
    habitat: "brackish",
    rarity: "uncommon",
    maxLengthCm: 150,
    regions: ["North Atlantic"],
    diet: "Insects, crustaceans, small fish",
    description: "Anadromous — returns from sea to natal rivers to spawn.",
  },
  {
    id: "striped-bass",
    dexNumber: 15,
    commonName: "Striped Bass",
    scientificName: "Morone saxatilis",
    habitat: "brackish",
    rarity: "uncommon",
    maxLengthCm: 200,
    regions: ["Atlantic coast of North America"],
    diet: "Herring, menhaden, eels",
    description: "Seven to eight dark horizontal stripes down each flank.",
  },
  {
    id: "parrotfish",
    dexNumber: 16,
    commonName: "Rainbow Parrotfish",
    scientificName: "Scarus guacamaia",
    habitat: "reef",
    rarity: "rare",
    maxLengthCm: 120,
    regions: ["Caribbean"],
    diet: "Algae, coral polyps",
    description: "Fused beak scrapes algae from coral. Sleeps in a mucus cocoon.",
  },
  {
    id: "lionfish",
    dexNumber: 17,
    commonName: "Red Lionfish",
    scientificName: "Pterois volitans",
    habitat: "reef",
    rarity: "uncommon",
    maxLengthCm: 47,
    regions: ["Indo-Pacific", "Invasive: Caribbean"],
    diet: "Small fish, crustaceans",
    description: "Fan-like pectorals and 18 venomous spines. Beautiful and dangerous.",
  },
  {
    id: "arapaima",
    dexNumber: 18,
    commonName: "Arapaima",
    scientificName: "Arapaima gigas",
    habitat: "freshwater",
    rarity: "legendary",
    maxLengthCm: 450,
    regions: ["Amazon Basin"],
    diet: "Fish, small mammals, birds",
    description: "Air-breathing giant of the Amazon. Surfaces every 20 minutes.",
  },
];

export const RARITY_META: Record<Rarity, { label: string; className: string }> = {
  common: { label: "Common", className: "bg-muted text-muted-foreground" },
  uncommon: { label: "Uncommon", className: "bg-[oklch(0.65_0.15_155)] text-[oklch(0.15_0.05_240)]" },
  rare: { label: "Rare", className: "bg-primary text-primary-foreground" },
  legendary: { label: "Legendary", className: "bg-accent text-accent-foreground" },
};

export const HABITAT_META: Record<Habitat, { label: string; icon: string }> = {
  freshwater: { label: "Freshwater", icon: "◈" },
  saltwater: { label: "Saltwater", icon: "≈" },
  brackish: { label: "Brackish", icon: "◊" },
  reef: { label: "Coral Reef", icon: "❋" },
  "deep-sea": { label: "Deep Sea", icon: "▼" },
};
